In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('Dataset_Day15.csv')
df.head(20)

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whole wheat pasta,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,soup,light cream,shallot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,frozen vegetables,spaghetti,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,eggs,pet food,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,turkey,burgers,mineral water,eggs,cooking oil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,spaghetti,champagne,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,mineral water,salmon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,mineral water,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,shrimp,chocolate,chicken,honey,oil,cooking oil,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,turkey,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,turkey,fresh tuna,tomatoes,spaghetti,mineral water,black tea,salmon,eggs,chicken,extra dark chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,meatballs,milk,honey,french fries,protein bar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,red wine,shrimp,pasta,pepper,eggs,chocolate,shampoo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# 1.	Read the data and remove all null or empty values.
from csv import reader

groceries =[]
with open('Dataset_Day15.csv','r') as csvfile:
    read = reader(csvfile)
    for row in read:
        row_new = [x for x in row if x!='NaN']
        groceries.append(row_new)

In [10]:
groceries[0:5]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers',
  'meatballs',
  'eggs',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['chutney',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['turkey',
  'avocado',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['mineral water',
  'milk',
  'energy bar',
  'whole wheat rice',
  'green tea',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']]

In [11]:
# 2.	Transform the data using TransactonEncoder to perform Market Basket Analysis.
from mlxtend.preprocessing import TransactionEncoder

encoder = TransactionEncoder()

transactions = encoder.fit(groceries).transform(groceries)
transactions

array([[False, False,  True, ...,  True, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False,  True, False]])

In [12]:
itemsets = pd.DataFrame(transactions, columns = encoder.columns_)

display(itemsets.head())
display(itemsets.info())

,,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,True,True,False,True,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Columns: 121 entries,  to zucchini
dtypes: bool(121)
memory usage: 886.5 KB

None

In [13]:
# 3.	 Use min_support = 0.02 to find frequent itemsets.

from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(itemsets, min_support = 0.02, use_colnames = True)
frequent_itemsets

      support                             itemsets
0    0.999867                                   ()
1    0.020397                            (almonds)
2    0.033329                            (avocado)
3    0.033729                           (brownies)
4    0.087188                            (burgers)
..        ...                                  ...
202  0.020131  (, whole wheat rice, mineral water)
203  0.022930             (, spaghetti, olive oil)
204  0.025197              (, spaghetti, pancakes)
205  0.021197                (, spaghetti, shrimp)
206  0.020931              (, spaghetti, tomatoes)

[207 rows x 2 columns]

In [14]:
frequent_itemsets.sort_values('support', ascending = False)

      support                             itemsets
0    0.999867                                   ()
35   0.238368                      (mineral water)
88   0.238235                    (, mineral water)
14   0.179709                               (eggs)
67   0.179709                             (, eggs)
..        ...                                  ...
152  0.020131    (whole wheat rice, mineral water)
202  0.020131  (, whole wheat rice, mineral water)
132  0.020131             (pancakes, french fries)
182  0.020131           (, pancakes, french fries)
121  0.020131         (cooking oil, mineral water)

[207 rows x 2 columns]

In [19]:
# 4.	Use the frequent itemsets to create association rules (take min_threshold as 15%) and evaluate the rules for the following metrics

from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.15)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(almonds),(),0.020397,0.999867,0.020264,0.993464,0.993597,-0.000131,0.020397,-0.006536
1,(avocado),(),0.033329,0.999867,0.033196,0.996000,0.996133,-0.000129,0.033329,-0.004000
2,(brownies),(),0.033729,0.999867,0.033729,1.000000,1.000133,0.000004,inf,0.000138
3,(burgers),(),0.087188,0.999867,0.087188,1.000000,1.000133,0.000012,inf,0.000146
4,(butter),(),0.030129,0.999867,0.030129,1.000000,1.000133,0.000004,inf,0.000137
...,...,...,...,...,...,...,...,...,...,...
316,"(spaghetti, shrimp)",(),0.021197,0.999867,0.021197,1.000000,1.000133,0.000003,inf,0.000136
317,(shrimp),"(, spaghetti)",0.071457,0.174110,0.021197,0.296642,1.703760,0.008756,1.174209,0.444850
318,"(, tomatoes)",(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117,0.462740
319,"(spaghetti, tomatoes)",(),0.020931,0.999867,0.020931,1.000000,1.000133,0.000003,inf,0.000136
320,(tomatoes),"(, spaghetti)",0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117,0.462740

In [24]:
# a.	Find top 5 antecedent -> consequent rules based on ‘conviction’, ‘leverage’, ‘lift’. Explain your findings.

top_rules_by_conviction = rules.nlargest(5, 'conviction')
top_rules_by_leverage = rules.nlargest(5, 'leverage')
top_rules_by_lift = rules.nlargest(5, 'lift')

print(top_rules_by_conviction)
print("************************")
print(top_rules_by_leverage)
print("************************")
print(top_rules_by_lift)

  antecedents consequents  antecedent support  consequent support   support  \
2  (brownies)          ()            0.033729            0.999867  0.033729
3   (burgers)          ()            0.087188            0.999867  0.087188
4    (butter)          ()            0.030129            0.999867  0.030129
5      (cake)          ()            0.081056            0.999867  0.081056
6   (cereals)          ()            0.025730            0.999867  0.025730

   confidence      lift  leverage  conviction  zhangs_metric
2         1.0  1.000133  0.000004         inf      -0.966271
3         1.0  1.000133  0.000012         inf      -0.912812
4         1.0  1.000133  0.000004         inf      -0.969871
5         1.0  1.000133  0.000011         inf      -0.918944
6         1.0  1.000133  0.000003         inf      -0.974270
************************
         antecedents      consequents  antecedent support  consequent support  \
110      (spaghetti)    (ground meat)            0.174110            0.098254
111    (ground meat)      (spaghetti)            0.098254            0.174110
268    (, spaghetti)    (ground meat)            0.174110            0.098254
269  (, ground meat)      (spaghetti)            0.098254            0.174110
271      (spaghetti)  (, ground meat)            0.174110            0.098254

      support  confidence      lift  leverage  conviction  zhangs_metric
110  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
111  0.039195    0.398915  2.291162  0.022088    1.373997       -0.35972
268  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
269  0.039195    0.398915  2.291162  0.022088    1.373997       -0.35972
271  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
************************
         antecedents      consequents  antecedent support  consequent support  \
110      (spaghetti)    (ground meat)            0.174110            0.098254
268    (, spaghetti)    (ground meat)            0.174110            0.098254
271      (spaghetti)  (, ground meat)            0.174110            0.098254
111    (ground meat)      (spaghetti)            0.098254            0.174110
269  (, ground meat)      (spaghetti)            0.098254            0.174110

      support  confidence      lift  leverage  conviction  zhangs_metric
110  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
268  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
271  0.039195    0.225115  2.291162  0.022088    1.163716       -0.18592
111  0.039195    0.398915  2.291162  0.022088    1.373997       -0.35972
269  0.039195    0.398915  2.291162  0.022088    1.373997       -0.35972

In [23]:
# b.	Find top 2 & bottom 2 antecedent -> consequent rules based on ‘zhang’s metric’. Explain your findings.

rules['zhangs_metric'] = rules['support'] - rules['confidence']

top_rules_by_zhangs_metric = rules.nlargest(2, 'zhangs_metric')
bottom_rules_by_zhangs_metric = rules.nsmallest(2, 'zhangs_metric')

print(top_rules_by_zhangs_metric)
print("************************")
print(bottom_rules_by_zhangs_metric)

   antecedents     consequents  antecedent support  consequent support  \
9           ()     (chocolate)            0.999867            0.163845
19          ()  (french fries)            0.999867            0.170911

     support  confidence      lift  leverage  conviction  zhangs_metric
9   0.163845    0.163867  1.000133  0.000022    1.000026      -0.000022
19  0.170911    0.170933  1.000133  0.000023    1.000027      -0.000023
************************
                      antecedents consequents  antecedent support  \
184  (cooking oil, mineral water)          ()            0.020131
227      (pancakes, french fries)          ()            0.020131

     consequent support   support  confidence      lift  leverage  conviction  \
184            0.999867  0.020131         1.0  1.000133  0.000003         inf
227            0.999867  0.020131         1.0  1.000133  0.000003         inf

     zhangs_metric
184      -0.979869
227      -0.979869